name: i_hear
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  carousel_slider: ^5.1.1
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dash_chat_2: ^0.0.21
  firebase_ai: ^3.1.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.3.0
  google_generative_ai: ^0.4.7
  google_maps_flutter: ^2.12.3
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.2
  video_player: ^2.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Icon/logoNew.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon.png
    - assets/images/op1.png
    - assets/images/op2.png
    - assets/images/op3.png
    - assets/images/op4.png
    - assets/images/ob1.png
    - assets/images/ob2.png
    - assets/images/ob3.png
    - assets/images/B1.png
    - assets/images/B2.png
    - assets/images/B3.png
    - assets/images/B4.png
    - assets/images/B5.png
    - assets/images/B6.png
    - assets/images/B7.png
    - assets/images/B8.png
    - assets/images/B9.png
    - assets/images/B10.png
    - assets/images/logingmbr.png
    - assets/Icon/ArtikelIcon.png
    - assets/Icon/CommunnityIcon.png
    - assets/Icon/HomeIcom.png
    - assets/Icon/ProfilIcon.png
    - assets/images/background.png
    - assets/images/fotoProfil.png
    - assets/Icon/NotifIcon.png
    - assets/Icon/Settings.png
    - assets/images/scroll frame.png
    - assets/Icon/translate.png
    - assets/Icon/voice.png
    - assets/Icon/abcd.png
    - assets/Icon/bot.png
    - assets/Icon/logoNewW.png
    - assets/Icon/Ls1.png
    - assets/Icon/Ls2.png
    - assets/Icon/Ls3.png
    - assets/Icon/Ls4.png
    - assets/Icon/Ls5.png
    - assets/Icon/botHome.png
    - assets/Icon/botbiru.png
    - assets/images/Berita1.png
    - assets/images/Berita2.png
    - assets/images/Iklan1.png
    - assets/images/Iklan2.png
    - assets/images/Iklan3.png
    - assets/Icon/ComunityIconNew.png
    - assets/Icon/PhotoIcon.png
    - assets/Icon/AR.png
    - assets/Icon/c1.png
    - assets/Icon/c2.png
    - assets/Icon/c3.png
    - assets/Icon/c4.png
    - assets/Icon/map.png
    - assets/Icon/botPosisi.png
    - assets/Icon/trainAwal.png
    - assets/Icon/trainTujuan.png
    - assets/Icon/logoNew.png
    - assets/images/newsCard1.png
    - assets/images/newsCard2.png
    - assets/images/newsCard3.png
    - assets/images/komunitas1.png
    - assets/images/komunitas2.png
    - assets/images/komunitas3.png
    - assets/images/komunitas4.png
    - assets/images/Ihearsosmed1.png
    - assets/images/Ihearsosmed2.png
    - assets/images/Ihearsosmed3.png
    - assets/images/loginBerhasil.png
    - assets/images/daftarBerhasil.png
    - assets/Icon/logoLiputan6.png
    - assets/Icon/logoSB.png
    - assets/Icon/logoTempo.png
    - assets/video/aku.mp4
    - assets/video/kamu.mp4
    - assets/video/terimaKasih.mp4
    - assets/video/apaKabar.mp4
    - assets/video/tuli.mp4
    - assets/video/samaSama.mp4
    - assets/video/BahasaIsyarat.mp4
    - assets/video/dengar.mp4
    - assets/video/dia.mp4
    - assets/video/kami.mp4
    - assets/video/kita.mp4
    - assets/video/perkenalkan.mp4
    - assets/video/umur.mp4
    - assets/video/SplashScreen.mp4
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
